#pragma once

#include <Statement/blockstatement.h>
#include <Statement/breakstatement.h>
#include <Statement/classdeclarationsstatement.h>
#include <Statement/continuestatement.h>
#include <Statement/dowhilestatement.h>
#include <Statement/exprstatement.h>
#include <Statement/foreacharraystatement.h>
#include <Statement/foreachmapstatement.h>
#include <Statement/forstatement.h>
#include <Statement/functiondefinestatement.h>
#include <Statement/ifstatement.h>
#include <Statement/importstatement.h>
#include <Statement/integrationstatement.h>
#include <Statement/printlnstatement.h>
#include <Statement/printstatement.h>
#include <Statement/returnstatement.h>
#include <Statement/switchstatement.h>
#include <Statement/throwstatement.h>
#include <Statement/trystatement.h>
#include <Statement/whilestatement.h>
